CREATE ROLE postgres WITH LOGIN SUPERUSER;

CREATE DATABASE nixos_blogs;
\c nixos_blogs postgres;

CREATE USER root WITH PASSWORD 'root';
GRANT ALL PRIVILEGES ON DATABASE nixos_blogs TO root;

CREATE USER backend WITH PASSWORD 'backend';
REVOKE ALL ON DATABASE nixos_blogs FROM backend;
GRANT CONNECT ON DATABASE nixos_blogs TO backend;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO backend;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO backend;

-- Add privileges on tables created after the user
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE ON SEQUENCES TO backend;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO backend;
