# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NodeJS Blogs CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: The Determinate Nix Installer
      uses: DeterminateSystems/nix-installer-action@v10
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v4
    - name: Checking Backend
      run: cd NixOSBlogs && nix develop --impure --command bash -c "cd nixos_blog_backend && yarn lint:ci"
    - name: Checking Frontend
      run: cd NixOSBlogs && nix develop --impure --command bash -c "cd nixos_blog_frontend && yarn lint:ci"

  Testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: The Determinate Nix Installer
      uses: DeterminateSystems/nix-installer-action@v10
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v4
    - name: Integration tests Backend
      run: cd NixOSBlogs && nix run .#testIntegration
